Line: Add EndpointSIPOptionsView table creation
wazo-platform/xivo-manage-db pull request #140
Opened 2021-10-28 13:28 UTC by ja0x

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/130

Creates the materialized view table in the database to be used
by the DAO

Why:

* Allows a faster way to query inherited options for each SIP endpoint
* Used to allow fast searching/sorting on callerid for linefeatures

2021-11-08 20:09 UTC, fblackburn1 requested changes

2021-11-12 17:34 UTC, ja0x commented on alembic/versions/5ffaec7e8db7_add_endpoint_sip_materialized_view.py
> +from xivo_dao.helpers.db_views import DDLCreateView, DDLDropView
Removed dependency and placed logic for CreateView/DropView inside migration script

2021-11-22 20:52 UTC, fblackburn1 approved these changes

2021-11-23 12:21 UTC, fblackburn1 commented
regate

2021-11-23 12:25 UTC, merged