Removed queue_info table and references.
wazo-platform/xivo-manage-db pull request #145
Opened 2021-11-22 15:34 UTC by vamenard

2021-11-22 20:28 UTC, bloom1 requested changes
Great :smiley: if you have any questions don't hesitate

2021-11-22 20:28 UTC, bloom1 commented on alembic/versions/203129d6b213_remove_queue_info_table.py
> +    pass
`pass` is only used when there is no body to a function: you can remove it (in both functions)

2021-11-22 20:28 UTC, bloom1 commented on alembic/versions/203129d6b213_remove_queue_info_table.py
> +        Column('caller_uniqueid', String(32), nullable=False, server_default='0'),
For `queue_name`, `caller` and `caller_uniqueid`: `server_default` should be an empty string, not `0`.

2021-11-22 20:28 UTC, bloom1 commented on alembic/versions/203129d6b213_remove_queue_info_table.py
> +        Column('queue_name', String(128), nullable=False, server_default='0'),
The `call_time_t` column is missing here

2021-11-22 20:28 UTC, bloom1 commented on alembic/versions/203129d6b213_remove_queue_info_table.py
> +    pass
You should also recreate the Indexes: (from the `xivo-dao` schema):
```python
class QueueInfo(Base):

    __tablename__ = 'queue_info'
    __table_args__ = (
        PrimaryKeyConstraint('id'),
        Index('queue_info_call_time_t_index', 'call_time_t'),
        Index('queue_info_queue_name_index', 'queue_name'),
# ...
```

2021-11-23 15:21 UTC, vamenard commented
recheck

2021-11-23 15:59 UTC, bloom1 approved these changes

2021-11-23 16:04 UTC, merged