Wazo 2266 remove get_queue_statistics sql function
wazo-platform/xivo-manage-db pull request #146
Opened 2021-11-24 01:44 UTC by vamenard

2021-11-24 15:15 UTC, fblackburn1 requested changes

2021-11-24 15:15 UTC, fblackburn1 commented on alembic/versions/241501a5f8ba_remove_queue_info_function.py
> +    op.drop_table('queue_info')
Please configure your IDE to run flake8 on every python file at each save or commit
W292 no newline at end of file

2021-11-24 15:15 UTC, fblackburn1 commented on alembic/versions/241501a5f8ba_remove_queue_info_function.py
> +    LANGUAGE SQL;
Please configure your IDE to run flake8 on every python file at each save or commit
W291 trailing whitespace

2021-11-24 15:15 UTC, fblackburn1 commented on alembic/versions/241501a5f8ba_remove_queue_info_function.py
> +        )
same comment about flake8
Fix indent

2021-11-25 14:16 UTC, bloom1 commented
Hello @vamenard!

Adding to what @fblackburn1 said, I don't think that it is necessary to have a working dowgrade in this case. Since this migration does not remove the table, it should not recreate it on downgrade. The queue statistics have not been present in Wazo since 18.03 (I think?) so they can be safely removed without a working dowgrade.

What do you think @fblackburn1?

2021-11-25 15:05 UTC, fblackburn1 commented
> Hello @vamenard!
> 
> Adding to what @fblackburn1 said, I don't think that it is necessary to have a working dowgrade in this case. Since this migration does not remove the table, it should not recreate it on downgrade. The queue statistics have not been present in Wazo since 18.03 (I think?) so they can be safely removed without a working dowgrade.
> 
> What do you think @fblackburn1?

Yep no objection. downgrade are more for development purpose, they are never used
And I agree in this case, running this downgrade AND the previous downgrade script, will raise a error because we try to create the same table twice

2021-11-25 15:34 UTC, fblackburn1 approved these changes
thanks, now https://jenkins.wazo.community/view/Failed/job/xivo-manage-db-check_migrations/
should be fixed

2021-11-25 15:40 UTC, bloom1 approved these changes

2021-11-25 15:40 UTC, bloom1 commented
regate

2021-11-25 15:42 UTC, bloom1 commented
recheck

2021-11-25 16:13 UTC, merged