Add fks with ondelete=cascade for user_line
wazo-platform/xivo-manage-db pull request #206
Opened 2023-07-05 20:05 UTC by xxbillouxx

2023-07-12 09:40 UTC, sduthil requested changes

2023-07-12 09:40 UTC, sduthil commented on alembic/versions/52d8c306e35f_add_fks_user_line.py
> +    op.execute('DELETE FROM linefeatures WHERE id NOT IN (SELECT DISTINCT line_id FROM user_line)')
I don't think those deletions are necessary, since the foreign key already ensures the data is valid, right?

2023-07-12 09:40 UTC, sduthil commented on alembic/versions/2f786b1077f9_add_fk_line_context.py
> +        None,
When adding a new foreign key, we should delete the potentially invalid data first.

2023-07-12 14:03 UTC, xxbillouxx commented on alembic/versions/2f786b1077f9_add_fk_line_context.py
> +        None,
I added a DELETE

2023-07-13 15:44 UTC, sduthil submitted a review, later dismissed

2023-07-13 15:49 UTC, sduthil approved these changes

2023-07-13 15:52 UTC, merged