Add ondelete=cascade for switchboard/member
wazo-platform/xivo-manage-db pull request #209
Opened 2023-07-07 17:24 UTC by xxbillouxx

2023-07-12 10:06 UTC, sduthil requested changes

2023-07-12 10:06 UTC, sduthil commented on alembic/versions/b4fb4eb3cf8e_add_delete_cascade_fk_switchboard_member.py
> +    op.execute('DELETE FROM switchboard WHERE uuid NOT IN (SELECT DISTINCT switchboard_uuid FROM switchboard_member_user)')
Those are not necessary, since the FK already existed, right?

2023-07-12 13:58 UTC, xxbillouxx commented on alembic/versions/b4fb4eb3cf8e_add_delete_cascade_fk_switchboard_member.py
> +    op.execute('DELETE FROM switchboard WHERE uuid NOT IN (SELECT DISTINCT switchboard_uuid FROM switchboard_member_user)')
You're right

2023-07-17 09:46 UTC, sduthil approved these changes

2023-07-17 09:49 UTC, merged