Add new table for features extensions
wazo-platform/xivo-manage-db pull request #216
Opened 2023-07-31 17:09 UTC by xxbillouxx

2023-08-01 17:10 UTC, xxbillouxx commented
recheck

2023-08-02 12:40 UTC, xxbillouxx commented
recheck

2023-08-02 14:32 UTC, xxbillouxx commented
recheck

2023-08-03 13:35 UTC, xxbillouxx commented
recheck

2023-08-08 15:08 UTC, pc-m requested changes

2023-08-08 15:08 UTC, pc-m commented on alembic/versions/1d5d4e41d708_move_features_extensions_dedicated_table.py
> +    op.create_index(
The index on the primary key is redundant. Postgresql creates an index for all primary keys

2023-08-08 15:08 UTC, pc-m commented on alembic/versions/1d5d4e41d708_move_features_extensions_dedicated_table.py
> +        TEXT 'extenfeatures' as type
Syntax error here
I think the line `TEXT 'extenfeatures' as type` needs a coma and the line `feature as typeval,` does not

2023-08-08 15:08 UTC, pc-m commented on alembic/versions/1d5d4e41d708_move_features_extensions_dedicated_table.py
> +        TEXT 'extenfeatures' as type
There's also a type error
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "type" is of type extenumbers_type but expression is of type text
LINE 7:         TEXT 'extenfeatures' as type,
```

2023-08-08 15:27 UTC, xxbillouxx commented on alembic/versions/1d5d4e41d708_move_features_extensions_dedicated_table.py
> +    op.create_index(
Explicit index removed

2023-08-09 14:27 UTC, pc-m commented
Looks good to me

2023-08-14 19:06 UTC, pc-m submitted a review, later dismissed

2023-08-14 19:26 UTC, fblackburn1 requested changes
don't forget to rebase alembic version (we should add a zuul check on this)

2023-08-14 19:27 UTC, pc-m commented
> don't forget to rebase alembic version (we should add a zuul check on this)

Wouldn't the `debian-packaging-bullseye` check fail during the gate?

2023-08-14 19:36 UTC, pc-m approved these changes

2023-08-14 20:00 UTC, merged

2023-08-14 20:53 UTC, fblackburn1 commented
> > don't forget to rebase alembic version (we should add a zuul check on this)
> 
> Wouldn't the `debian-packaging-bullseye` check fail during the gate?

Oh maybe :man_shrugging: