Added migration to clean up incall extensions in limbo
wazo-platform/xivo-manage-db pull request #258
Opened 2024-04-09 21:29 UTC by DrPyser

why: those extensions are disassociated but unavailable, caused by user recursive delete improperly deleting incalls

2024-04-11 10:44 UTC, sduthil requested changes

2024-04-11 10:44 UTC, sduthil commented on alembic/versions/b38ce53a1d32_remove_incall_extensions_in_limbo.py
> +            extensions_table.c.context.ilike('%from-extern')
This is not reliable enough to detect incall contexts. The `context` table has a column `contexttype` with the value `incalls` that we can rely on.

2024-04-11 10:44 UTC, sduthil commented on alembic/versions/b38ce53a1d32_remove_incall_extensions_in_limbo.py
> +        extensions_table.c.id.in_(query.alias())
Why do we need a subquery here? Can't we do the filtering directly in the `DELETE` statement?

2024-04-15 17:34 UTC, DrPyser commented on alembic/versions/b38ce53a1d32_remove_incall_extensions_in_limbo.py
> +        extensions_table.c.id.in_(query.alias())
Yep, certainly could. I was using this structure to insert a select statement for testing, and thought the separation was appropriate for readability and maintainability(e.g. if needed to change, easier to safely test). Can change it.

2024-04-16 10:17 UTC, sduthil approved these changes

2024-04-16 10:31 UTC, merged