stat_queue: add tenant uuid
wazo-platform/xivo-manage-db pull request #83
Opened 2020-09-29 19:53 UTC by sduthil

2020-10-02 15:24 UTC, pc-m commented
recheck

2020-10-05 12:22 UTC, fblackburn1 requested changes
stat_queue.id is not the same ID than queuefeatures.id (probably same thing for stat_agent, I didn't check)

You must match queue name, I will do another PR to add the real queue_id in the stat_queue table (needed for the API PATH)

2020-10-06 16:28 UTC, fblackburn1 requested changes
queue id is already handle by https://github.com/wazo-platform/xivo-manage-db/pull/84

2020-10-06 18:00 UTC, pc-m approved these changes

2020-10-06 18:00 UTC, pc-m approved these changes

2020-10-06 18:01 UTC, merged